from typing import Protocol, runtime_checkable


@runtime_checkable
class DBRepository(Protocol):
    def save(self, collection: str, record: dict) -> None: ...
    def find_all(self, collection: str) -> list[dict]: ...
    def find_by_id(self, collection: str, record_id: str) -> dict | None: ...
    def clear(self, collection: str) -> None: ...
    def count(self, collection: str) -> int: ...
